### ISSUE TITLE
[CS 카르텔] 컴퓨터 구조 1-5 장 논의

### ISSUE THREAD

**Issue by le2sky** [2024-woowacourse-study/level-interview#256]
컴구 5장 아톰 제안
주소지정
명령어 사이클
명령어 파이프라인
cisc risc

컴구 5장 망쵸 제안
CPU 성능 높이는 방법 (큰그림)
- 클럭수 높이기
- 코어수 높이기
- 멀티코어 멀티스레드
- 파이프라이닝
파이프라인 + 해저드 3가지
명령어 병렬 처리 기법 3가지
cisc, risc 차이
클럭수를 높인다고 무지성 빨라질까? 
코어 수를 늘린다고 빨라질까? 

합의점
- 명령어 사이클
- Cpu 성능 향상 큰 그림
- 명령어 병렬 처리 기법
- 명령어 파이프라인과 해저드
- cisc, risc

**Comment by 3Juhwan** [comment]
나이쓰 👍

**Comment by le2sky** [comment]
- level 1
- level 2
- level 3
    - 컴퓨터 구조
        - ....
    - 운영체제
    - 자바 병렬 프로그래밍

요런 느낌?

**Comment by 3Juhwan** [comment]
굉장히 좋습니다 뭐든 하고 보죠

**Comment by 3Juhwan** [comment]
> 1. 레벨 인터뷰 이슈를 올리고 거기에서 합의점 찾는다.
> 2. 합의점을 기반으로 PR을 생성한다. (README 업데이트와 디스커션 틀 만들기)
> 3. 수요일까지 작성한다.

백스윙에서 얘기했던 대로 각 주제에 대해 각자 정리하기로 가나요?

**Comment by le2sky** [comment]
넹. 디스커션 파고 있는데 각 디스커션에 같이 쓰는 느낌을 생각하고 있어요.
좋은 방법있나여?

**Comment by 3Juhwan** [comment]
좋습니다. 생각한 대로에요
